### ISSUE TITLE
Fails if a track's image is 'None'

### ISSUE THREAD

**Issue by ViciousBadger** [phijor/mopidy-notify#1]
```
ERROR    2023-08-08 13:30:15,290 [27475:NotifyFrontend-18 (_actor_loop)] mopidy.listener
  Triggering event failed: track_playback_started(tl_track)
Traceback (most recent call last):
  File "/home/abadger/.local/lib/python3.11/site-packages/mopidy/listener.py", line 44, in on_event
    getattr(self, event)(**kwargs)
  File "/home/abadger/.local/lib/python3.11/site-packages/mopidy_notify/frontend.py", line 43, in track_playback_started
    self.show_notification(tl_track)
  File "/home/abadger/.local/lib/python3.11/site-packages/mopidy_notify/frontend.py", line 75, in show_notification
    icon = self.fetch_icon(track.uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abadger/.local/lib/python3.11/site-packages/mopidy_notify/frontend.py", line 127, in fetch_icon
    preferred = self.find_preferred_image(images)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abadger/.local/lib/python3.11/site-packages/mopidy_notify/frontend.py", line 107, in find_preferred_image
    acceptable = [i for i in images if i.width <= self.ext_config["max_icon_size"]]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abadger/.local/lib/python3.11/site-packages/mopidy_notify/frontend.py", line 107, in <listcomp>
    acceptable = [i for i in images if i.width <= self.ext_config["max_icon_size"]]
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
```

It seems that some Mopidy backends will supply an icon with each track, but the icons are all 'None' objects. mopidy-notify does not expect this and throws an exception instead of ignoring the invalid image.
So far I've had this happen with every track from the following backends:

- mopidy-youtube
- mopidy-podcast
- mopidy-somafm

**Comment by phijor** [comment]
Hi, thanks for reporting the issue! I've looked into it, and it doesn't seem like the backends are doing anything wrong. In fact, Mopidy [verifies](https://github.com/mopidy/mopidy/blob/f3efcac4fb96ff07f9cd801732e5b1059bacb463/mopidy/core/library.py#L219) the images returned by backends.

What I think happens is that some backends return images where `width = None`. I'll try to fix that.
